# Generated by Django 6.0.6 on 2026-08-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MirrorDatabaseState",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
                ("source_host", models.CharField(blank=True, default="", max_length=255)),
                ("source_database", models.CharField(blank=True, default="", max_length=63)),
                ("retain_cutoff", models.DateField(blank=True, null=True)),
                ("dumpling_version", models.CharField(blank=True, default="", max_length=64)),
                ("dumpling_config_sha256", models.CharField(blank=True, default="", max_length=64)),
                ("dumpling_report", models.JSONField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Mirror database state",
                "verbose_name_plural": "Mirror database state",
            },
        ),
    ]
