# Generated by Django 6.0.8 on 2026-08-17

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MirrorDatabaseState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "generated_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When refresh_database_mirror last finished loading this database.",
                        null=True,
                    ),
                ),
                (
                    "source_host",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Hostname of the dump source (no credentials).",
                        max_length=255,
                    ),
                ),
                (
                    "source_database",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Database name of the dump source.",
                        max_length=63,
                    ),
                ),
                (
                    "retain_cutoff",
                    models.DateField(
                        blank=True,
                        help_text="Row-retain cutoff date applied during generation, if any.",
                        null=True,
                    ),
                ),
                (
                    "dumpling_version",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Dumpling CLI version from the generation report, when available.",
                        max_length=64,
                    ),
                ),
                (
                    "dumpling_config_sha256",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="SHA-256 of the effective Dumpling config from the generation report.",
                        max_length=64,
                    ),
                ),
                (
                    "dumpling_report",
                    models.JSONField(
                        blank=True,
                        help_text="Dumpling --report JSON provenance sidecar from the last generation.",
                        null=True,
                    ),
                ),
                (
                    "restored_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When restore_from_mirror last completed cutover onto this database.",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Mirror database state",
                "verbose_name_plural": "Mirror database state",
            },
        ),
    ]
